### ISSUE TITLE
Automated actions not triggered

### ISSUE THREAD

**Issue by pawangeek** [python-geeks/Automation-scripts#129]
**Describe the bug**
After PR of the all-contributors bot, I added an automated action for the labeler(.github/workflow/labeler.yml) workflow which is not working

**Expected behavior**
It should add **automerge** tag to PR as mentioned in .github/label-pr.yml

**Comment by Kartik-byte** [comment]
Hey, can you be a little more specific?
Like which type of files you are targeting for auto label . According to your regex in label-pr.yml it is targeting files with extension - {.docs , .contributors}.
Thank you.

**Comment by pawangeek** [comment]
No, not it's not with targetting files, it matches a pattern with a description of the issue (having docs and contributors in the description)

Here is the [link](https://github.com/marketplace/actions/pr-label-by-files) for that

**Comment by Kartik-byte** [comment]
Yeah that is true but I think that GitHub action is not looking for description of a issue, it is looking at the filenames in the committed PR so unless it finds a file with a extension {.docs , .contributors} (according to your regex) it wont add a tag to the PR.
### Configuration

Create a file into your root project directory: `.github/label-pr.yml`:
```yaml
- regExp: ".*\\.ts+$"
  labels: ["typescript"]
- regExp: ".*\\.sql+$"
  labels: ["database", "critical"]
- regExp: ".*\\.md+$"
  labels: ["documentation"]
- regExp: "^(pom\\.xml|package\\.json|build\\.gradle)$"
  labels: ["dependencies"]
- regExp: ".*\\.(zip|jar|war|ear)+$"
  labels: ["artifact", "invalid"]
```
_This is a sample to illustrate how you can customize your settings by configuring your own regex and labels_

The configuration is made of a list of `Filter` which are composed of:
- `regExp`: a regular expression which will be tested over the <ins>filenames</ins>
- `labels`: a list of labels to apply if the filenames match
